---
title: "Proyecto Procesamiento de Datos"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Primer Proyecto - Emily Bolaños Carvajal - C01213 - Manuel Vargas

```{r echo=TRUE, message=FALSE, warning=FALSE, librerías, echo=FALSE, paged.print=FALSE}
library(ggplot2)
library(hrbrthemes)
library(grid)
library(gridExtra)
library(stringr)
library(dplyr)
library(scales)
```


## Limpiar los datos 
```{r Sirva_porfis, echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
Igbebe <- read.csv("liberia_datos_climaticos.csv", sep = ",", na.strings = "", dec = ",")
Igbebe[!complete.cases(Igbebe),]
Igbebe <- na.omit(Igbebe)
```
##### Con los datos limpios de N/A se prosigue con el cambio de nombres de las variables


## Cambiar nombres de la variables
```{r nombres, echo=TRUE}
names (Igbebe) = c("Fecha", "Temperatura", "Humedad", "Viento", "Lluvia", "Irradiación", "Evapotranspiración")
names (Igbebe)
```

#Graficación de los datos climáticos
## Graficación de histogramas
```{r echo=FALSE, fig.height=10, fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
grid.arrange(
ggplot(Igbebe, aes(y= Temperatura, group = 1)) +
  geom_histogram(
    col = "#F8A91C",
    fill = "#FAC462"
  ) + 
  ggtitle("Variación Temperatura") +
  xlab("Data") +
  ylab("Temperatura °C") +
  theme_ipsum(
    axis_text_size = 8,
    ticks = TRUE, 
    axis = "y",
    grid = "Y,y"
  ),
ggplot(Igbebe, aes(y= Humedad, group = 1)) + 
  geom_histogram(
    col = "#26EE94",
    fill = "#10C674"
  ) + 
  ggtitle("Variación Humedad") +
  xlab("Data") +
  ylab("Humedad %") +
  theme_ipsum(
    axis_text_size = 8,
    ticks = TRUE, 
    axis = "y",
    grid = "Y,y"
  ),
ggplot(Igbebe, aes(y= Viento, group = 1)) + 
  geom_histogram(
    col = "#91BCEF",
    fill = "#6DA9B7"
  ) +
  ggtitle("Velocidad del Viento") +
  xlab("Data") +
  ylab("Viento m/s") +
  theme_ipsum(
    axis_text_size = 8,
    ticks = TRUE, 
    axis = "y",
    grid = "Y,y"
  ),
ggplot(Igbebe, aes(y= Lluvia, group = 1)) + 
  geom_histogram(
    col = "#1E307C",
    fill = "#848DBA"
  ) + 
  ggtitle("Cantidad de Lluvia") +
  xlab("Data") +
  ylab("Lluvia mm") +
  theme_ipsum(
    axis_text_size = 8,
    ticks = TRUE, 
    axis = "y",
    grid = "Y,y"
  ),
ggplot(Igbebe, aes(y= Irradiación, group = 1)) + 
  geom_histogram(
    col = "#B67D30",
    fill = "#D39D55"
  ) + 
  ggtitle("Variación Irradiación") +
  xlab("Data") +
  ylab("Irradiación km2") +
  theme_ipsum(
    axis_text_size = 8,
    ticks = TRUE, 
    axis = "y",
    grid = "Y,y"
  ),
ggplot(Igbebe, aes(y= Evapotranspiración, group = 1)) + 
  geom_histogram(
    col = "#ECEC14",
    fill = "#F0F04E"
  ) +
  ggtitle("Variación Evapotranspiración") +
  xlab("Data") +
  ylab("Evapotranspiración mm") +
  theme_ipsum(
    axis_text_size = 8,
    ticks = TRUE, 
    axis = "y",
    grid = "Y,y"
  ))
```

```{r promedios, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
Promedios <- 
  Igbebe %>%
select(Fecha, Temperatura, Humedad, Viento, Lluvia, Irradiación, Evapotranspiración)%>%
mutate (Fecha = as.Date(Fecha, format = "%d/%m/%Y"))%>%
group_by(Fecha = format(Fecha, "%Y"))%>%
summarise(Temperatura = mean(Temperatura), Humedad = mean(Humedad),
          Viento = mean(Viento), Lluvia = sum(Lluvia),
          Irradiación = mean(Irradiación), Evapotranspiración = sum(Evapotranspiración))
```


## Gráficos de líneas y puntos por año
```{r fig.height=10, fig.width=10, message=FALSE, warning=FALSE, paged.print=FALSE}
grid.arrange(ggplot(Promedios, aes(x=Fecha, y=Temperatura, group = 1, colour = Temperatura)) + 
   geom_line(col = "#F8A91C",
             fill = "#F8A91C") +
     ggtitle("Variación Temperatura") +
     xlab("Año") +
     ylab("Temperatura °C") +
   geom_point() +
   theme_ipsum(ticks = TRUE, 
               axis = "y",
               grid = "Y,y"),
ggplot(Promedios, aes(x=Fecha, y=Humedad, group = 1, colour = Humedad)) + 
   geom_line(col = "#26EE94",
             fill = "#26EE94") +
  ggtitle("Variación Humedad") +
  xlab("Año") +
  ylab("Humedad %") + 
   geom_point() +
   theme_ipsum(ticks = TRUE, 
               axis = "y",
               grid = "Y,y"),
ggplot(Promedios, aes(x=Fecha, y=Viento, group = 1, colour = Viento)) + 
   geom_line(col = "#91BCEF",
             fill = "#91BCEF") + 
  ggtitle("Velocidad del Viento") +
  xlab("Año") +
  ylab("Viento m/s") +
   geom_point() +
   theme_ipsum(ticks = TRUE, 
               axis = "y",
               grid = "Y,y"),
ggplot(Promedios, aes(x=Fecha, y=Lluvia, group = 1, colour = Lluvia)) + 
   geom_line(col = "#1E307C",
             fill = "#1E307C") + 
  ggtitle("Cantidad de Lluvia") +
  xlab("Año") +
  ylab("Lluvia mm") +
   geom_point() +
   theme_ipsum(ticks = TRUE, 
               axis = "y",
               grid = "Y,y"),
ggplot(Promedios, aes(x=Fecha, y=Irradiación, group = 1, colour = Irradiación)) + 
   geom_line(col = "#B67D30",
             fill = "#B67D30") + 
  ggtitle("Variación Irradiación") +
  xlab("Año") +
  ylab("Irradiación km2") +
   geom_point() +
   theme_ipsum(ticks = TRUE, 
               axis = "y",
               grid = "Y,y"),
ggplot(Promedios, aes(x=Fecha, y=Evapotranspiración, group = 1, colour = Evapotranspiración)) + 
   geom_line(col = "#ECEC14",
             fill = "#ECEC14") + 
  ggtitle("Variación Evapotranspiración") +
  xlab("Año") +
  ylab("Evapotranspiración mm") +
   geom_point() +
   theme_ipsum(ticks = TRUE, 
               axis = "y",
               grid = "Y,y"))
```

